language: python

python:
  - "2.7"
  # - "3.2" Temporary disabling Python3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git

install:
  - pip install argparse
  - pip install beaker
  - pip install bottle
  - pip install coveralls
  - pip install mock
  - pip install netaddr
  - pip install paramiko
  - pip install pytest
  - pip install pytest-cov
  - pip install setproctitle
  - pip install webtest
  - pip install -e .

script:
  - py.test tests/test.py tests/test_cli.py tests/test_webapp.py -v --cov firelet --cov-report term-missing

after_success:
  - coveralls
