language: python

python:
  - "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git
 - sudo apt-get install -qq libxml2-dev
 - sudo apt-get install -qq libxslt1-dev
 - sudo apt-get install -qq lib32z1-dev

install:
  - "python setup.py install"
  - pip install coveralls
  - pip install tox
  - pip install -e .

script: tox

after_success:
  - coveralls
